/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package check_radion;

import javax.swing.JLabel;

/**
 *
 * @author TuanMatHeo
 */
public class radio_button extends javax.swing.JFrame {

    /**
     * Creates new form radio_button
     */
    public radio_button() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ra1 = new javax.swing.JRadioButton();
        ra2 = new javax.swing.JRadioButton();
        ra3 = new javax.swing.JRadioButton();
        ra4 = new javax.swing.JRadioButton();
        ra5 = new javax.swing.JRadioButton();
        btvote = new javax.swing.JButton();
        lbkq = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Ví dụ Radion_Button");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Bạn có thích anh ấy không?");

        buttonGroup1.add(ra1);
        ra1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ra1.setText("Rất thích");

        buttonGroup1.add(ra2);
        ra2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ra2.setText("Hơi hơi thích");
        ra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ra3);
        ra3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ra3.setText("Không lung lay");

        buttonGroup1.add(ra4);
        ra4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ra4.setText("Nhìn mặt thấy ghét");
        ra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ra4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ra5);
        ra5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ra5.setText("Nhìn mặt muốn báo công an");

        btvote.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btvote.setText("Vote");
        btvote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoteActionPerformed(evt);
            }
        });

        lbkq.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ra1)
                            .addComponent(jLabel2)
                            .addComponent(ra2)
                            .addComponent(ra3)
                            .addComponent(ra4)
                            .addComponent(btvote)
                            .addComponent(ra5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lbkq)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ra3)
                .addGap(6, 6, 6)
                .addComponent(ra4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ra5)
                .addGap(18, 18, 18)
                .addComponent(btvote)
                .addGap(18, 18, 18)
                .addComponent(lbkq)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ra2ActionPerformed

    private void ra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ra4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ra4ActionPerformed

    private void btvoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoteActionPerformed
        if(ra1.isSelected())
        {
            lbkq.setText("Rất thích");
        }
        else if(ra2.isSelected())
        {
            lbkq.setText("Hơi hơi thích");
        }
        else if(ra3.isSelected())
        {
            lbkq.setText("Không lung lay");
        }
        else if(ra4.isSelected())
        {
            lbkq.setText("Nhìn mặt thấy ghét");
        }
        else if(ra5.isSelected())
        {
            lbkq.setText("Nhìn mặt muốn báo công an");
        }
    }//GEN-LAST:event_btvoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radio_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radio_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radio_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radio_button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radio_button().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btvote;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbkq;
    private javax.swing.JRadioButton ra1;
    private javax.swing.JRadioButton ra2;
    private javax.swing.JRadioButton ra3;
    private javax.swing.JRadioButton ra4;
    private javax.swing.JRadioButton ra5;
    // End of variables declaration//GEN-END:variables
}
